[package]
name = "craigslist-scraper"
version = "0.1.0"
authors = ["Dylan Johnson <dylanatasmsa@gmail.com>"]

[dependencies]
hyper = "0.7.2"
html5ever = "0.5.3"
tendril = "0.2.2"
getopts = "0.2"
rustc-serialize = "0.3.19"
slack = "0.15.0"

[lib]
name = "lib"
path = "src/lib/lib.rs"
